name: generate animation

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allows manual run from Actions tab
  workflow_dispatch:

  # Run on push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Generate GitHub contribution graph SVGs
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push SVGs to the output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          committer: "Todixx <not.todixxx@gmail.com>"
          author: "Todixx <not.todixxx@gmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
